#  ПОДАТОЧНИ ТИПОВИ, ВЛЕЗ И ИЗЛЕЗ НА ПОДАТОЦИ

# print("Hello")
# print("Vnesi godini")
# x = int(input())
# print(f"{x}")
# print(type(x))

# print(2**2)

# upper()
# poraka = "     pytHon 1 cOuRse ab ababab aba"
# poraka_upper = poraka.upper()
# print(poraka_upper)
# # lower()
# poraka_lower = poraka_upper.lower()
# print(poraka_lower)
# # capitalize()
# capitalize_poraka = poraka.capitalize()
# print(capitalize_poraka)
# # swapcase()
# swapcase_poraka = poraka.swapcase()
# print(swapcase_poraka)
# # title()
# title_poraka = poraka.title()
# # count()
# h_count = poraka.count("ab")
# print(h_count)
# # endswith()
# print(poraka.endswith("a"))
# print(poraka.endswith("aba"))
# print(poraka.endswith("abaa"))
# # find()
# py = poraka.find("py")
# print(py)
# py = poraka.find("t")
# print(py)
# py = poraka.find("a")
# print(py)
# py = poraka.find("34567")
# print(py)
# # index()
# #py = poraka.index("a", 17, 20)
# print(py)
# # isalpha()
# print(('b').isalpha())
# print(('1').isalpha())
# # isdecimal()
# print(('b').isdecimal())
# print(('1').isdecimal())
# # isdigit()
# print(('b').isdigit())
# print(('1').isdigit())
# # islower()
# print('A'.islower())
# print('x'.islower())
# # isupper()
# print('A'.isupper())
# print('x'.isupper())
# # isnumeric()
# print('afs'.isnumeric())
# print('12'.isnumeric())
# print('1.4'.isnumeric())
# # split()
# poraka_split = poraka.split(" ")
# print(poraka_split)
# # strip()
# poraka_strip = poraka.strip()
# print(poraka_strip)
# # replace()
# poraka_replace = poraka.replace("1", "2")
# print(poraka_replace)
# #
# poraka_2 = "Python 2 course\nWelcome\tto this course"
# print(poraka_2)
#
# lista_programski_jazici = ["python", "c", "c#", "c++", "c", "c++", "c++", "php", "java"]
#
# # append()
# lista_programski_jazici.append("c")
# print(lista_programski_jazici)
# # clear()
# #lista_programski_jazici.clear()
# #print(lista_programski_jazici)
# # copy()
# lpj_copy = lista_programski_jazici.copy()
# # count()
# c_jazik = lpj_copy.count("c")
# print(c_jazik)
# # extend()
# lpj_2 = ["javascript", "c#"]
# lpj_copy.extend(lpj_2)
# print(lpj_copy)
# # insert()
# lpj_copy.insert(2, "kotlin")
# print(lpj_copy)
# # pop()
# lpj_copy.pop(3)
# print(lpj_copy)
# # remove()
# lpj_copy.remove("c#")
# print(lpj_copy)
# # reverse()
# lpj_copy.reverse()
# print(lpj_copy)
# # sort()
# lpj_copy.sort()
# print(lpj_copy)
# lpj_copy.reverse()
# print(lpj_copy)
# # index()
# indeks_kotlin = lpj_copy.index("kotlin")
# print(indeks_kotlin)
# lpj_copy[1] = "php_v.2"
# print(lpj_copy)
# #len
# print(len(lpj_copy))
#
# # remove duplicates
# lpj_copy = list(set(lpj_copy))
# print(lpj_copy)

poraka_2 = "Python 2 course\nWelcome\t\t\tto        this course"
print(poraka_2)

l1 = 'TTACCGGACGTTACCGGACGTTACCGGACGTTTTAAT'
l2 = 'TTACCGGACGTTACCGGACGTTACCGGACGAATTAAC'

print(len(l1))

for i in range(len(l1)):
    if l1[i] != l2[i]:
        print(f"{i+74}. {l1[i]} - {l2[i]}")
